// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2D97XHFEdAYv8uwG9A6UuZAtnyDksA8',
    appId: '1:881609309616:web:a061d0cabf53e162246a75',
    messagingSenderId: '881609309616',
    projectId: 'clinical-6802c',
    authDomain: 'clinical-6802c.firebaseapp.com',
    storageBucket: 'clinical-6802c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9it8OF-QYDWf0mRdBMksDnKc7685DLTw',
    appId: '1:881609309616:android:dd3fb83214faadc7246a75',
    messagingSenderId: '881609309616',
    projectId: 'clinical-6802c',
    storageBucket: 'clinical-6802c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzXZtcIH2rM2uug6l8r7xCoehbEFpV_48',
    appId: '1:881609309616:ios:f3e3b4f0ca50c27b246a75',
    messagingSenderId: '881609309616',
    projectId: 'clinical-6802c',
    storageBucket: 'clinical-6802c.appspot.com',
    iosBundleId: 'com.example.clinical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzXZtcIH2rM2uug6l8r7xCoehbEFpV_48',
    appId: '1:881609309616:ios:f3e3b4f0ca50c27b246a75',
    messagingSenderId: '881609309616',
    projectId: 'clinical-6802c',
    storageBucket: 'clinical-6802c.appspot.com',
    iosBundleId: 'com.example.clinical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG2D97XHFEdAYv8uwG9A6UuZAtnyDksA8',
    appId: '1:881609309616:web:45d4c3602ad59c5e246a75',
    messagingSenderId: '881609309616',
    projectId: 'clinical-6802c',
    authDomain: 'clinical-6802c.firebaseapp.com',
    storageBucket: 'clinical-6802c.appspot.com',
  );
}
